// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameItem = "item"

// Item mapped from table <item>
type Item struct {
	ID      string `gorm:"column:id;primaryKey" json:"id"`
	Name    string `gorm:"column:name" json:"name"`
	Desc    string `gorm:"column:desc" json:"desc"`
	Confirm string `gorm:"column:confirm" json:"confirm"`
}

// TableName Item's table name
func (*Item) TableName() string {
	return TableNameItem
}
